---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# yadngd: Yet Another /dev/null Graphic Device using extendr

This repository is for testing [extendr/extendr#360](https://github.com/extendr/extendr/pull/360)

<!-- badges: start -->
<!-- badges: end -->

## Installation

```{r eval=FALSE}
remotes::install_github("yutannihilation/yadngd")
```

## Usage

```{r}
library(yadngd)

yadngd("◆祝◆ device activated!!! ◆祝◆", show_message = TRUE)

# "yadgnd" is on the list
dev.list()

# do nothing
plot(1)

# close the device
dev.off()
```

## Performance

(The code is from [r-lib/devoid](https://github.com/r-lib/devoid))

```{r}
library(devoid)

point_coord <- seq_len(1e4)

void_plot <- function() {
  void_dev()
  plot(point_coord, point_coord)
  dev.off()
  NULL
}

yadngd_plot <- function() {
  yadngd("", show_message = FALSE)
  plot(point_coord, point_coord)
  dev.off()
  NULL
}

res <- bench::mark(
  devoid = void_plot(),
  yadngd = yadngd_plot(),
  min_iterations = 50
)

res[, 1:9]

plot(res)
```

