# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_yadngd_wrappers", use_symbols = TRUE, package_name = "yadngd")

#' @docType package
#' @usage NULL
#' @useDynLib yadngd, .registration = TRUE
NULL

#' Return string `"Hello world!"` to R.
#' @export
yadngd <- function(welcome_message) .Call(wrap__yadngd, welcome_message)

