# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_yadngd_wrappers", use_symbols = TRUE, package_name = "yadngd")

#' @docType package
#' @usage NULL
#' @useDynLib yadngd, .registration = TRUE
NULL

#' A graphic device that does nothing
#'
#' @param welcome_message A warm message to welcome you.
#' @param show_message Whether to show the welcome message.
#' @export
yadngd <- function(welcome_message, show_message) invisible(.Call(wrap__yadngd, welcome_message, show_message))

